//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueBoAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminControl
    {
        public int AdminControlID { get; set; }
        public int AdminID { get; set; }
        public string AdminContent { get; set; }
        public Nullable<int> ReportID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime RecordTime { get; set; }
        public Nullable<int> PostID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Post Post { get; set; }
    }
}
