//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueBoAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentID { get; set; }
        public string ContentPic { get; set; }
        public string ContentDesc { get; set; }
        public System.DateTime ContentTime { get; set; }
        public int FatherContentID { get; set; }
        public int UserID { get; set; }
        public int PostID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
