//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueBoAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YueBoDB : DbContext
    {
        public YueBoDB()
            : base("name=YueBoDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<AdminControl> AdminControl { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<Follow> Follow { get; set; }
        public virtual DbSet<Forward> Forward { get; set; }
        public virtual DbSet<Like> Like { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostStatus> PostStatus { get; set; }
        public virtual DbSet<PostType> PostType { get; set; }
        public virtual DbSet<PrivateMessage> PrivateMessage { get; set; }
        public virtual DbSet<PrivateMessageDetail> PrivateMessageDetail { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReportType> ReportType { get; set; }
        public virtual DbSet<SensitiveWord> SensitiveWord { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserLabel> UserLabel { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<UserTypeDetail> UserTypeDetail { get; set; }
    }
}
