//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueBoMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessageDetail
    {
        public int PrivateMessageDetailID { get; set; }
        public int PrivateMessageID { get; set; }
        public string PrivateMessageContent { get; set; }
        public System.DateTime PrivateMessageTime { get; set; }
        public bool IsRead { get; set; }
    
        public virtual PrivateMessage PrivateMessage { get; set; }
    }
}
