//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueBoMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrivateMessage()
        {
            this.PrivateMessageDetail = new HashSet<PrivateMessageDetail>();
        }
    
        public int PrivateMessageID { get; set; }
        public int UserID { get; set; }
        public int PrivateMessageUserID { get; set; }
        public bool IsBan { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateMessageDetail> PrivateMessageDetail { get; set; }
    }
}
