//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueBoMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public int UserID { get; set; }
        public int PostID { get; set; }
        public int ReportTypeID { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsSeccess { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
