//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YueBoMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypeDetail
    {
        public int UserTypeDetailID { get; set; }
        public int UserID { get; set; }
        public int UserTypeID { get; set; }
        public string ReviewPic { get; set; }
        public int IsAuthentication { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
